### ISSUE TITLE
SHA256 signed payload benchmark doesn't work

### ISSUE THREAD

**Issue by stefreak** [flangner/s3bench#4]
At least with Quobyte 1.3.21

```
# SHA256 signed payload benchmark
## single stream latency
Object size: 4.00 KiB

method, min, max, avg, throughput (based on avg), ops/s (based on avg), operation count
put, 27.39 ms, 269.63 ms, 88.19 ms, 46.45 Kb/s, 11.34 /s, 10.00
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 665716920319324252; S3 Extended Request ID: null), S3 Extended Request ID: null
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 665716920319324252; S3 Extended Request ID: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1592)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4227)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4174)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1382)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1259)
	at com.quobyte.s3bench.S3BenchmarkClient$GetClient.sampleRun(S3BenchmarkClient.java:136)
	at com.quobyte.s3bench.S3BenchmarkClient$Sampler.run(S3BenchmarkClient.java:70)
	at com.quobyte.s3bench.S3BenchmarkClient.singleStreamReadPerformance(S3BenchmarkClient.java:211)
	at com.quobyte.s3bench.S3BenchmarkClient.singleStreamPerformanceTest(S3BenchmarkClient.java:174)
	at com.quobyte.s3bench.S3BenchmarkClient.main(S3BenchmarkClient.java:465)
```

**Comment by flangner** [comment]
This is actually an issue with the Quobyte S3 Service that got fixed in recent versions (release 1.4 onward).
